### ISSUE TITLE
Missing dependency aurelia-path

### ISSUE THREAD

**Issue by tipa** [aurelia/hot-module-reload#6]
The package is missing the dependency "aurelia-path". I currently have it to add manually.

**Comment by EisenbergEffect** [comment]
Ping @niieani

**Comment by niieani** [comment]
Ah, seems you're correct. Would you like to make a PR with the fix @tipa?

**Comment by tipa** [comment]
I never did a PR before and messing around with it a bit wasn't successful, so I am afraid to say that I cannot make one, sorry.

**Comment by niieani** [comment]
OK, no problem. I'll fix it before the next release. This is not really a big problem since you need `aurelia-path` is installed by `aurelia-framework`.

**Comment by MeirionHughes** [comment]
steal... 💃

**Comment by niieani** [comment]
:) thanks!
